dist: focal
language: node_js
node_js:
  - "18"

services:
  - docker

cache:
  directories:
    - frontend/node_modules
    - backend/node_modules

branches:
  only:
    - main # Запуск тільки при пуші в гілку main

before_install:
  - cd frontend
  - npm install -g @angular/cli
  - cd ..

install:
  - cd frontend/compressApp
  - npm install
  - cd ../../backend
  - npm install
  - cd ..

script:
  # Збірка frontend та запуск тестів
  - cd frontend/compressApp
  - npm test
  - npm run build
  - cd ../../

  # Створення Docker-образу
  - docker build -t $DOCKER_USERNAME/compress-app:latest .

after_success:
  # Логін до Docker Hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  # Тегування Docker-образу
  - docker tag $DOCKER_USERNAME/compress-app:latest $DOCKER_USERNAME/compress-app:latest

  # Пуш Docker-образу у Docker Hub
  - docker push $DOCKER_USERNAME/compress-app:latest
