language: node_js
node_js:
  - "18"

cache:
  directories:
    - frontend/node_modules
    - backend/node_modules

branches:
  only:
    - main

before_install:
  - npm config set unsafe-perm true
  - npm config set progress false || true
  - cd frontend
  - npm install -g @angular/cli
  - cd ..

install:
  - cd frontend/compressApp
  - npm install
  - cd ../../backend
  - npm install
  - cd ..

script:
  - cd frontend/compressApp
  - npm run build
  - cd ../../

  - cd backend
  - npm test
  - cd ..
