dist: focal
language: node_js
node_js:
  - "18" # Виберіть версію Node.js

services:
  - docker

cache:
  directories:
    - frontend/node_modules
    - backend/node_modules

branches:
  only:
    - main

before_install:
  - cd frontend
  - npm install -g @angular/cli
  - cd ..

install:
  - cd frontend/compressApp
  - npm install
  - cd ../../backend
  - npm install
  - cd ..

script:
  # Збірка frontend та запуск тестів
  - cd frontend/compressApp
  - npm run build
  - cd ../../

  # Створення Docker-образу
  - docker build -t $REGION-docker.pkg.dev/$GCP_PROJECT_ID/$REPOSITORY_NAME/compress-app-img .
  # Тегування образу
  - docker tag $REGION-docker.pkg.dev/$GCP_PROJECT_ID/$REPOSITORY_NAME/compress-app-img $REGION-docker.pkg.dev/$GCP_PROJECT_ID/$REPOSITORY_NAME/compress-app-img:compressapp

after_success:
  # Декодування ключа облікового запису служби Google Cloud
  - echo "$GCLOUD_SERVICE_KEY"  > ${HOME}/gcloud-service-key.json

  # Аутентифікація у Google Cloud
  - gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
  - gcloud --quiet config set project $GCP_PROJECT_ID
  - gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

  # Створення репозиторію (пропустіть цей крок, якщо репозиторій вже створений)
  - gcloud artifacts repositories create $REPOSITORY_NAME \
    --repository-format=docker \
    --location=$REGION || echo "Репозиторій вже існує"

  - docker build -t $REGION-docker.pkg.dev/$GCP_PROJECT_ID/$REPOSITORY_NAME/compress-app-img .

  # Тегування Docker-образу
  - docker tag $LOCAL_IMAGE_NAME $REGION-docker.pkg.dev/$GCP_PROJECT_ID/$REPOSITORY_NAME/compress-app-img:latest

  # Пуш Docker-образу у Google Artifact Registry
  - docker push $REGION-docker.pkg.dev/$GCP_PROJECT_ID/$REPOSITORY_NAME/compress-app-img:latest
