dist: focal
language: node_js
node_js:
  - "18" # Виберіть версію Node.js

services:
  - docker

cache:
  directories:
    - frontend/node_modules
    - backend/node_modules

branches:
  only:
    - main

before_install:
  - cd frontend
  - npm install -g @angular/cli
  - cd ..

install:
  - cd frontend/compressApp
  - npm install
  - cd ../../backend
  - npm install
  - cd ..

script:
  # Збірка frontend та запуск тестів
  - cd frontend/compressApp
  - npm run build
  - cd ../../

  # Створення Docker-образу
  - docker build -t gcr.io/$GCP_PROJECT_ID/compress-app-img .

after_success:
  # Декодування ключа облікового запису служби Google Cloud
  - echo "$GCLOUD_SERVICE_KEY" | base64 --decode > ${HOME}/gcloud-service-key.json

  # Аутентифікація у Google Cloud
  - gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
  - gcloud --quiet config set project $GCP_PROJECT_ID
  - gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

  # Пуш Docker-образу у Google Artifact Registry
  - docker push $REGION-docker.pkg.dev/$GCP_PROJECT_ID/$REPOSITORY_NAME/compress-app-img
