version: "3.8"
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app_network
    depends_on:
      - mongo
  selenium-chrome:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
  selenium-firefox:
    image: selenium/standalone-firefox
    ports:
      - "4445:4444"

volumes:
  mongo_data:

networks:
  app_network:
    driver: bridge
