language: node_js
node_js:
  - "22" # Виберіть версію Node.js

cache:
  directories:
    - node_modules # Кешування залежностей для прискорення процесу збірки

branches:
  only:
    - main # Запуск Travis CI тільки для гілки main

install:
  - npm install # Встановлення всіх залежностей, визначених у package.json

script:
  - npm run lint # Лінтинг для перевірки якості коду
  - npm test # Запуск тестів
  - npm run build # Збірка проєкту
  - npm run serve:ssr:compressApp # Запуск SSR-сервера після збірки для тестування

notifications:
  email:
    recipients:
      - gitmongonode2022@gmail.com # Замініть на вашу електронну пошту
    on_success: change # Отримувати повідомлення лише у разі зміни статусу
    on_failure: always # Отримувати повідомлення при будь-якій невдачі збірки
