version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:22.8.0-browsers
    steps:
      - checkout
      - run: node --version

      # Встановлення залежностей та підготовка середовища
      - run:
          name: Install Angular CLI
          command: |
            cd frontend
            npm install @angular/cli
            cd ..

      # Встановлення залежностей frontend та backend
      - run:
          name: Install Dependencies
          command: |
            cd frontend/compressApp
            npm install --no-package-lock
            cd ../../backend
            npm install --no-package-lock
            cd ..

      # Збереження кешу
      - save_cache:
          paths:
            - frontend/node_modules
            - backend/node_modules
      # Установка chrome
      - run:
          name: Install Chrome
          command: |
            sudo apt-get update
            sudo apt-get install -y wget gnupg
            wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable
      # Запуск тестів та збірка frontend
      - run:
          name: Run Tests and Build Frontend
          command: |
            cd frontend/compressApp
            npm test
            npm run build
            cd ../../

      # Створення Docker-образу
      - setup_remote_docker:
          version: "default"
      - run:
          name: Build Docker Image
          command: docker build -t $DOCKER_USERNAME/compress-app:latest .

      # Логін у Docker Hub та пуш образу
      - run:
          name: Push Docker Image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker tag $DOCKER_USERNAME/compress-app:latest $DOCKER_USERNAME/compress-app:latest
            docker push $DOCKER_USERNAME/compress-app:latest

workflows:
  version: 2
  build_and_push:
    jobs:
      - build:
          filters:
            branches:
              only: main
