version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout

      # Кешування node_modules
      - restore_cache:
          keys:
            - v1-frontend-node-modules-{{ checksum "frontend/compressApp/package.json" }}
            - v1-backend-node-modules-{{ checksum "backend/package.json" }}

      # Встановлення залежностей та підготовка середовища
      - run:
          name: Install Angular CLI
          command: |
            cd frontend
            npm install -g @angular/cli
            cd ..

      # Встановлення залежностей frontend та backend
      - run:
          name: Install Dependencies
          command: |
            cd frontend/compressApp
            npm install --no-package-lock
            cd ../../backend
            npm install --no-package-lock
            cd ..

      # Збереження кешу
      - save_cache:
          paths:
            - frontend/compressApp/node_modules
            - backend/node_modules
          key: v1-frontend-node-modules-{{ checksum "frontend/compressApp/package.json" }}-backend-node-modules-{{ checksum "backend/package.json" }}

      # Запуск тестів та збірка frontend
      - run:
          name: Run Tests and Build Frontend
          command: |
            cd frontend/compressApp
            npm test
            npm run build
            cd ../../

      # Створення Docker-образу
      - setup_remote_docker: version
